FROM ubuntu:22.04
WORKDIR /app
COPY runMeDB.out /app/runMeDB.out
COPY flightScanner.sh /app/flightScanner.sh
RUN apt-get update && apt-get install -y \
	libzip4 zip curl
RUN chmod +x /app/flightScanner.sh

CMD ./runMeDB.out
